// This file is automatically generated by FontCodeGenerator.
// Please copy it in Image source directory.
#ifndef Image_FontSymbols_H
#define Image_FontSymbols_H

namespace sg {
namespace image {
namespace symbols {
namespace {
    size_t const FullStar             = 33;
    size_t const SmallStar            = 34;
    size_t const Star                 = 35;
    size_t const EyedStar             = 36;
    size_t const Info                 = 37;
    size_t const Minimized            = 38;
    size_t const Windowed             = 39;
    size_t const Maximized            = 40;
    size_t const ThinObliqueCross     = 41;
    size_t const ObliqueCross         = 42;
    size_t const ThickObliqueCross    = 43;
    size_t const RightArrow           = 44;
    size_t const RightDoubleArrow     = 45;
    size_t const LeftArrow            = 46;
    size_t const LeftDoubleArrow      = 47;
    size_t const DownArrow            = 48;
    size_t const DownDoubleArrow      = 49;
    size_t const UpArrow              = 50;
    size_t const UpDoubleArrow        = 51;
    size_t const Plus                 = 52;
    size_t const Minus                = 53;
    size_t const Eye                  = 58;
    size_t const Brush                = 61;
    size_t const ThickBrush           = 62;
    size_t const Pencil               = 63;
    size_t const Sword                = 64;
    size_t const EmptyPotion          = 65;
    size_t const Potion               = 66;
    size_t const EmptyBigPotion       = 67;
    size_t const BigPotion            = 68;
    size_t const Shield               = 69;
    size_t const ShieldWithBand       = 70;
    size_t const UncheckedBox         = 80;
    size_t const CheckedBox           = 81;
    size_t const UncheckedRadioButton = 82;
    size_t const CheckedRadioButton   = 83;
}
}
}
}

#endif
