#ifndef ObjectScript_Tokenizer_Include_CharTraits
#error "this file must be used only by Tokenizer.h"
#endif

namespace sg {
namespace objectscript {
namespace {
//=============================================================================
struct CharTraits
{
#if SG_ENABLE_ASSERT
    char character;
#endif
    bool canBeginIdentifier : 1;
    bool canComposeIdentifier : 1;
    bool canComposeNumber : 1;
    bool canBeginSeparator : 1;
    u8 tokenIfUniqueAsu8;
    TokenType tokenIfUnique() const { return static_cast<TokenType>(tokenIfUniqueAsu8); }
};
//'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
#if SG_ENABLE_ASSERT
#define DEFINE_CHAR_TRAITS(CHAR, CAN_BEGIN_ID, CAN_COMPOSE_ID, CAN_COMPOSE_NUMBER, CAN_BEGIN_SEPARATOR, TOKEN_IF_UNIQUE) \
    { CHAR, CAN_BEGIN_ID, CAN_COMPOSE_ID, CAN_COMPOSE_NUMBER, CAN_BEGIN_SEPARATOR, static_cast<u8>(TOKEN_IF_UNIQUE) }
#else
static_assert(sizeof(CharTraits) <= 2, "CharTraits is too big");
#define DEFINE_CHAR_TRAITS(CHAR, CAN_BEGIN_ID, CAN_COMPOSE_ID, CAN_COMPOSE_NUMBER, CAN_BEGIN_SEPARATOR, TOKEN_IF_UNIQUE) \
    { CAN_BEGIN_ID, CAN_COMPOSE_ID, CAN_COMPOSE_NUMBER, CAN_BEGIN_SEPARATOR, static_cast<u8>(TOKEN_IF_UNIQUE) }
#endif
//'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
// let's begin at a line ending with 0.
CharTraits const charTraits[] = {
    //                    c  beg.Id   in Id  numb. beg.sep.       token if unique
    DEFINE_CHAR_TRAITS( '\0', false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS( '\t', false,  false, false,  true, TokenType::unknown ),
    DEFINE_CHAR_TRAITS( '\n', false,  false, false,  true, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS( '\r', false,  false, false,  true, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(  ' ', false,  false, false,  true, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(  '$', false,  false, false, false, TokenType::operator_dollar ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(  '(', false,  false, false, false, TokenType::open_parenthesis ),
    DEFINE_CHAR_TRAITS(  ')', false,  false, false, false, TokenType::close_parenthesis ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(  ',', false,  false, false, false, TokenType::operator_comma ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(  '.', false,  false, false, false, TokenType::operator_dot ),
    DEFINE_CHAR_TRAITS(  '/', false,  false, false,  true, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(  '0', false,   true,  true, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(  '1', false,   true,  true, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(  '2', false,   true,  true, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(  '3', false,   true,  true, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(  '4', false,   true,  true, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(  '5', false,   true,  true, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(  '6', false,   true,  true, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(  '7', false,   true,  true, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(  '8', false,   true,  true, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(  '9', false,   true,  true, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(  ';', false,  false, false, false, TokenType::operator_semicolon ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(  '?', false,  false, false, false, TokenType::operator_interrogation ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(  'A',  true,   true, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(  'B',  true,   true, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(  'C',  true,   true, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(  'D',  true,   true, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(  'E',  true,   true, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(  'F',  true,   true, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(  'G',  true,   true, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(  'H',  true,   true, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(  'I',  true,   true, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(  'J',  true,   true, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(  'K',  true,   true, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(  'L',  true,   true, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(  'M',  true,   true, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(  'N',  true,   true, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(  'O',  true,   true, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(  'P',  true,   true, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(  'Q',  true,   true, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(  'R',  true,   true, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(  'S',  true,   true, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(  'T',  true,   true, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(  'U',  true,   true, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(  'V',  true,   true, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(  'W',  true,   true, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(  'X',  true,   true, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(  'Y',  true,   true, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(  'Z',  true,   true, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(  '[', false,  false, false, false, TokenType::open_bracket ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(  ']', false,  false, false, false, TokenType::close_bracket ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(  '_',  true,   true, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(  'a',  true,   true, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(  'b',  true,   true, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(  'c',  true,   true, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(  'd',  true,   true, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(  'e',  true,   true, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(  'f',  true,   true, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(  'g',  true,   true, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(  'h',  true,   true, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(  'i',  true,   true, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(  'j',  true,   true, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(  'k',  true,   true, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(  'l',  true,   true, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(  'm',  true,   true, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(  'n',  true,   true, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(  'o',  true,   true, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(  'p',  true,   true, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(  'q',  true,   true, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(  'r',  true,   true, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(  's',  true,   true, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(  't',  true,   true, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(  'u',  true,   true, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(  'v',  true,   true, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(  'w',  true,   true, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(  'x',  true,   true, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(  'y',  true,   true, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(  'z',  true,   true, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(  '{', false,  false, false, false, TokenType::open_bloc ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(  '}', false,  false, false, false, TokenType::close_bloc ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
    DEFINE_CHAR_TRAITS(    0, false,  false, false, false, TokenType::unknown ),
};
size_t const charTraitsCount = SG_ARRAYSIZE(charTraits);
static_assert(256 == charTraitsCount, "incorrect number of charTraits!");
//=============================================================================
}
}
}
